# SERVER CONFIGURATION
# We use 8081 so it doesn't collide with your backend running on 8080
server.port=8080
spring.application.name=book-partner-frontend

# THYMELEAF CONFIGURATION
# Disable caching so you don't have to restart the server when you edit HTML
spring.thymeleaf.cache=false